### ISSUE TITLE
Styling suggestions

### ISSUE THREAD

**Issue by mich97** [aaraar/web-app-from-scratch-1920#1]
- Spacing between cards on smaller resolution
- Search country
- Display more stations by adding columns

**Comment by aaraar** [comment]
Will fix in later stage

**Comment by aaraar** [comment]
Fixed: https://github.com/aaraar/web-app-from-scratch-1920/blob/85c8d7b18b27b0964181c2b22f2fc4117753ae9e/src/scss/stations.scss#L4
