### ISSUE TITLE
shorter names, better readability?

### ISSUE THREAD

**Issue by joostf** [aaraar/web-app-from-scratch-1920#2]
https://github.com/aaraar/web-app-from-scratch-1920/blob/61b7b617429ccc9e13433dd62562d0f6ffb664a8/src/pages/Station.ts#L9

In a class named `Station` variables could be named leaner, `code` instead of `stationCode` and `name` instead of `stationName`...

**Comment by aaraar** [comment]
Yes, of course, thanks!
Will fix in next commit
