### ISSUE TITLE
What is 'this'?

### ISSUE THREAD

**Issue by joostf** [aaraar/web-app-from-scratch-1920#4]
https://github.com/aaraar/web-app-from-scratch-1920/blob/61b7b617429ccc9e13433dd62562d0f6ffb664a8/docs/js/app.js#L96

Do you know why the `_this = this;` pattern is used here?

**Comment by aaraar** [comment]
It binds the object 'this' to a variable to use it later when this gets rebinded

To try and explain it as well as possible within context:
It assigns the binded this in the function scope to a lexical scoped variable called _this so it can be used later outside that original self invoking function in the adjacent function to assign it properties from the promise. It simulates classes for cross browser support.

**Comment by joostf** [comment]
Well explained!

I would reckon the pattern is part of the inner workings of classes, rather than simulating them. Classes are syntactic sugar for prototypal inherritance..
