### ISSUE TITLE
IIFE

### ISSUE THREAD

**Issue by deannabosschert** [aaraar/web-app-from-scratch-1920#7]
# IIFE
Vgm heb je (nog) geen IIFE's in je code zitten, mss interesting om toe te passen? 👀 
Dunno of Typescript daar al wat mee doet tho.

https://developer.mozilla.org/en-US/docs/Glossary/IIFE

**Comment by aaraar** [comment]
Thanks for the tip, will not work on this for now but will look into it later if it has uses in the project. The typescript compiler does use it yes, to simulate some ES6 functionality
